version: '3.1'
  
services:
  sql_server:
    container_name: SQLServerExamen
    build: 
      context: .
      target: SQLExamen
    ports:
      - 1402:1433
    volumes:
      - ./filedb/SQLServer/:/var/opt/mssql/data/
    restart: always