SELECT * FROM PENDIENTES, PENDIENTEDETALLES WHERE PENDIENTES.PEND_ID = PENDIENTEDETALLES.PENDET_ID AND PENDIENTEDETALLES.PENDET_ID = 2;

SELECT SUM(VENTA_TOTAL) AS TOTAL FROM VENTASMAESTRO  WHERE VENTA_TURNO = 1 ;

SELECT * FROM PROD_CASA WHERE CASA_FECHA >= '2023-04-01' AND CASA_FECHA <= '2023-05-16';